name: ${project.name}
description: sudo
version: ${project.version}
api-version: "1.17"
main: io.github.silvigarabis.thesudo.TheSudoPlugin
authors: [Silvigarabis]
depend: [Luckperms]
commands:
  esplitter:
    description: ${project.name} main command
    usage: 'Usage: /<command> [args]
permissions:
  thesudo.sudo:
    description: can sudo
    default: false
  thesudo.help:
    description: can get help message about ${project.name}
    default: true
